-- Converted from SQLite by @profullstack/libsql-pg. Review every TODO before applying.
-- Types: INTEGER -> bigint, REAL -> double precision, BLOB -> bytea, BOOLEAN -> boolean,
-- DATETIME/TIMESTAMP -> timestamptz, TEXT -> text; INTEGER PRIMARY KEY -> identity.

create table social_posts (
  id text PRIMARY KEY,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  campaign_id text REFERENCES campaigns(id) ON DELETE CASCADE,
  person_id text REFERENCES people(id) ON DELETE CASCADE,
  recommendation_id text REFERENCES recommendations(id) ON DELETE SET NULL,
  network text NOT NULL,
  body text NOT NULL,
  url text,
  share_url text NOT NULL,
  opened_at text NOT NULL,
  confirmed_at text
);

CREATE INDEX idx_social_posts_ws ON social_posts(workspace_id, opened_at DESC);

CREATE INDEX idx_social_posts_person ON social_posts(person_id, opened_at DESC);

create table workflow_events (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id text NOT NULL,
  workspace_id text NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  campaign_id text REFERENCES campaigns(id) ON DELETE CASCADE,
  person_id text REFERENCES people(id) ON DELETE CASCADE,
  phase text NOT NULL,
  level text NOT NULL DEFAULT 'info',
  message text NOT NULL,
  detail_json text NOT NULL DEFAULT '{}',
  occurred_at text NOT NULL
);

CREATE INDEX idx_workflow_events_ws ON workflow_events(workspace_id, seq DESC);

CREATE INDEX idx_workflow_events_campaign ON workflow_events(campaign_id, seq DESC);
